### DISCUSSION TITLE
[Feature Request] More template support

### DISCUSSION THREAD

**Discussion by Selim042** [kinghat/tabbed-card#134] [Feature Requests]
With the new todo device type, I immediately went to make tabs for different todo lists with templates to fill values, but templates don't seem to be supported in the label or icon attributes.  I attached a screenshot of what is being displayed, and what I would expect as well as the yaml I would expect to work using templates.

```
type: custom:tabbed-card
tabs:
  - card:
      type: shopping-list
      entity: todo.shopping_list
    attributes:
      label: '{{ state_attr(''todo.shopping_list'',''friendly_name'') }}'
      icon: '{{ state_attr(''todo.shopping_list'',''icon'') }}'
```

Displayed:
![image](https://github.com/kinghat/tabbed-card/assets/8419844/fe68bb4e-3003-45ad-8750-3ff678bbc6eb)

Expected:
![image](https://github.com/kinghat/tabbed-card/assets/8419844/b0ad9e23-1e94-4aae-8b8c-ea14ecfd59e3)
