### DISCUSSION TITLE
Multiple pictiure cards in a row

### DISCUSSION THREAD

**Discussion by IIIdefconIII** [kinghat/tabbed-card#155] [Feature Requests]
Hi there, todat i installed this card for the first time:
I would like to know if its possible to put more picture cards in single row?

```
type: custom:tabbed-card
options: {}
tabs:
  - card:
      type: picture
      image: /local/card_headers/activeinsight.svg
      tap_action:
        action: url
        url_path: https://insight.synology.com/login
      entity: sun.sun
    attributes:
      label: Server
  - card:
      type: entity
      entity: sun.sun
    attributes:
      label: 2
  - card:
      type: entity
      entity: sun.sun
    attributes:
      label: 3
  - card:
      type: entity
      entity: sun.sun
    attributes:
      label: 4
  - card:
      type: entity
      entity: sun.sun
    attributes:
      label: 5
```
Would be nice to add a dew more items in there.

![image](https://github.com/user-attachments/assets/9b6906e1-3526-41b6-832a-7a646c87c324)

**Comment by IIIdefconIII** [comment]
kinda experimenting and got it this far with glances

```
type: custom:tabbed-card
options: {}
tabs:
  - card:
      type: picture
      image: /local/card_headers/activeinsight.svg
      tap_action:
        action: url
        url_path: https://insight.synology.com/login
      entity: sun.sun
    attributes:
      label: Server
  - card:
      type: glance
      title: Air Quality
      entities:
        - entity: sensor.069c0242_985afc9b_browser_path
          name: test
          image: /local/card_headers/activeinsight.svg
          show_state: false
          show_name: false
          tap_action: 
            action: url
            url_path: https://google.com
        - entity: sensor.069c0242_985afc9b_browser_useragent
          name: test2
          image: /local/card_headers/activeinsight.svg
          show_state: false
          show_name: false          
          tap_action: 
            action: url
            url_path: https://google.com          
      attributes:
        label: Air Quality
    attributes:
      label: 2
  - card:
      type: entity
      entity: sun.sun
    attributes:
      label: 3
  - card:
      type: entity
      entity: sun.sun
    attributes:
      label: 4
  - card:
      type: entity
      entity: sun.sun
    attributes:
      label: 5
```
![image](https://github.com/user-attachments/assets/daca112a-aa63-4882-a9c6-31455d7989b9)
