### DISCUSSION TITLE
feature: set card size to largest tab

### DISCUSSION THREAD

**Discussion by kinghat** [kinghat/tabbed-card#26] [Feature Requests]
the card currently doesnt set a constant size of the largest tab so it dynamically adjusts for each tab. add a static size option that sets the size of the card to the largest card in the config.

**Comment by ildar170975** [comment]
Vote for this.
May be useful currently in cases like that: https://github.com/kinghat/tabbed-card/issues/137

As an example:
```
type: custom:stack-in-card
cards:
  - type: entities
    entities:
      - entity: input_boolean.test_boolean
  - type: custom:tabbed-card
    tabs:
      - attributes:
          label: sun
        card:
          type: conditional
          conditions:
            - condition: state
              entity: input_boolean.test_boolean
              state: 'on'
          card:
            type: entity
            entity: sun.sun
      - attributes:
          label: zone
        card:
          type: entity
          entity: zone.home
```
A card on the the 1st tab is not shown, so the whole look is not nice:

![изображение](https://github.com/kinghat/tabbed-card/assets/71872483/2cab38cc-a46d-42a7-86b3-a2d81b52b4dc)

![изображение](https://github.com/kinghat/tabbed-card/assets/71872483/7ee408d6-67d1-41c7-839f-a166c9bd828e)
