### DISCUSSION TITLE
Labels don't render

### DISCUSSION THREAD

**Discussion by ackstorm23** [kinghat/tabbed-card#65] [Q&A] [answered]
Labels never render for me.  The tabs exist, but there is no text rendered on them. 

Is this a bug or do I have invalid syntax?

```
type: custom:tabbed-card
tabs:
  - card:
      type: entities
      entities:
        - entity: light.dimmable_smart_plug
          type: custom:light-brightness-preset-row
          customSetpoints: true
          lowBrightness: 25
          medBrightness: 100
          hiBrightness: 255
        - entity: light.dimmable_smart_plug_2
          type: custom:light-brightness-preset-row
          customSetpoints: true
          lowBrightness: 25
          medBrightness: 100
          hiBrightness: 255
        - entity: light.dimmable_smart_plug_3
          type: custom:light-brightness-preset-row
          customSetpoints: true
          lowBrightness: 25
          medBrightness: 100
          hiBrightness: 255
        - entity: light.dimmable_smart_plug_5
          type: custom:light-brightness-preset-row
          customSetpoints: true
          lowBrightness: 25
          medBrightness: 100
          hiBrightness: 255
      attributes:
        label: Upstairs

  - card:
      type: entities
      entities:
        - entity: light.dimmable_led_light_bulb
          type: custom:light-brightness-preset-row
          customSetpoints: true
          lowBrightness: 20
          medBrightness: 64
          hiBrightness: 255
        - entity: light.dimmable_gls0006_1
          type: custom:light-brightness-preset-row
          customSetpoints: true
          lowBrightness: 64
          medBrightness: 128
          hiBrightness: 255
        - entity: light.dimmable_sengled_1
          type: custom:light-brightness-preset-row
          customSetpoints: true
          lowBrightness: 20
          medBrightness: 64
          hiBrightness: 255
        - entity: light.dimmable_smart_plug_4
          type: custom:light-brightness-preset-row
          customSetpoints: true
          lowBrightness: 64
          medBrightness: 128
          hiBrightness: 255
        - entity: light.dimmable_flood_1
          type: custom:light-brightness-preset-row
          customSetpoints: true
          lowBrightness: 25
          medBrightness: 100
          hiBrightness: 255
        - entity: light.dimmable_flood_2
          type: custom:light-brightness-preset-row
          customSetpoints: true
          lowBrightness: 25
          medBrightness: 100
          hiBrightness: 255
      attributes:
        label: Downstairs
```
