### DISCUSSION TITLE
[FR] an option to manage text-transform

### DISCUSSION THREAD

**Discussion by ildar170975** [kinghat/tabbed-card#84] [Feature Requests]
Currently labels are "uppercase".
Please add an option to disable it.

[Managed to achieve it by card-mod](https://community.home-assistant.io/t/card-mod-add-css-styles-to-any-lovelace-card/120744/4280?u=ildar_gabdullin):
![image](https://user-images.githubusercontent.com/71872483/219114386-9a5469c3-7e21-4806-b292-8750039d66ac.png)
```
type: custom:mod-card
card_mod:
  style:
    tabbed-card $:
      mwc-tab:
        $: |
          .mdc-tab__text-label {
            text-transform: none;
          }
card:
  type: custom:tabbed-card
  attributes:
    icon: mdi:circle
  tabs:
    - card:
        <<: &ref_card
          type: entities
          entities:
            - sun.sun
      attributes:
        label: Label 1
    - card:
        <<: *ref_card
      attributes:
        label: Label 2
    - card:
        <<: *ref_card
      attributes:
        label: Label 3
```
