### DISCUSSION TITLE
Add Tooltip

### DISCUSSION THREAD

**Discussion by Mariusthvdb** [kinghat/tabbed-card#86] [Feature Requests]
please consider adding a tooltip option to the tabs.
Using an icon only tabbed config (because the labels are not resizable and force us to swipe the tabs) it would be really nice to have a tooltip on hovering.
Just like the tooltip in the main header bar

if it could be done with configurable transition, even better

using this myself on all button-cards to give you an idea:
```
  styles:
    tooltip:
      - transition: opacity 0.5s. # <-- main concern here, and makes the tooltip immediate
      - color: var(--card-background-color)
      - font-size: 12px
      - background: var(--primary-color)
      - padding: 5px
      - border-width: 0px
```
thanks for considering!

**Comment by kinghat** [comment]
i wont promise anything. im trying to just keep to the features that the material design tab component offers while integrating ha cards into it. that said, it sounds like your main issue is not being able to identify tabs. can you post a screenshot and the config of your tabbed-card?

**Reply by Mariusthvdb** [reply]
no, its not a matter of not being able to identify, it's more a matter of some closer explanation, and, having a consistent front-end throughout. All tabs in the Dash have these tooltips, so having a set without feels a bit awkward.

<img width="437" alt="Scherm­afbeelding 2023-02-16 om 16 02 17" src="https://user-images.githubusercontent.com/33354141/219426072-210bcba9-f4ec-4380-b7ea-8f33a0d270ab.png">


top, is the main header bar, below it the tabbed-card (notice the slight color difference? the colors are identical however in the yaml...)

**Reply by Mariusthvdb** [reply]
```
type: custom:tabbed-card
#       attributes:
#         isFadingIndicator: true
styles:
  --mdc-theme-primary: gold
  --mdc-tab-color-default: var(--text-primary-color)
tabs:
  - card:
      type: custom:decluttering-card
      template: picture_glance_area

    attributes:
#             label: Laundry
      icon: mdi:washing-machine
#             stacked: true
  - card:
      type: custom:decluttering-card
      template: picture_glance_area

    attributes:
#             label: Keuken
      icon: mdi:coffee
  - card:
      type: custom:decluttering-card
      template: picture_glance_area

    attributes:
#             label: Dining
      icon: mdi:silverware
  - card:
      type: custom:decluttering-card
      template: picture_glance_area

    attributes:
#             label: Auditorium
      icon: mdi:theater
```

is the main config body

would only need changing `label` to `tooltip ` and we wouldn't suffer the fact that using labels causes the tabs go beyond the card limits.

and I will have 4 of these in a vertical stack or so (replacing the swipe card completely...)
