### DISCUSSION TITLE
[Feature] Dynamic labels

### DISCUSSION THREAD

**Discussion by dzikimarian** [kinghat/tabbed-card#94] [Feature Requests]
I think that would be helpful to have dynamic data in label text. Then if you have multiple tabs (eg. various temperature graphs in each of them). You can see current temperature directly in the label. That will save you some time if, at the moment, you need only current state and not full card.

I've provided sample implementation here: https://github.com/kinghat/tabbed-card/pull/92 - fell free to let me know, what do you think about it.

**Comment by kinghat** [comment]
thanks for opening the feature request. im going to move it to the discussion area were the other feature requests are held.

**Comment by ildar170975** [comment]
Meanwhile - this functionality may be implemented by card-mod:
https://community.home-assistant.io/t/card-mod-add-css-styles-to-any-lovelace-card/120744/4280
![image](https://user-images.githubusercontent.com/71872483/222251756-1013e5dc-2330-409d-8074-d65df0eabc78.png)
![image](https://user-images.githubusercontent.com/71872483/222251775-d7080b96-0a85-4465-9fa5-e351c858b87d.png)

**Comment by Selim042** [comment]
This would be great if it also works for tab icons as well, very handy with the auto-entities card

**Reply by kinghat** [reply]
im sorry, if i could have merged these two i would have. please copy over your examples from your post for future reference :pray:

**Reply by Selim042** [reply]
From https://github.com/kinghat/tabbed-card/discussions/134:

----
With the new todo device type, I immediately went to make tabs for different todo lists with templates to fill values, but templates don't seem to be supported in the label or icon attributes.  I attached a screenshot of what is being displayed, and what I would expect as well as the yaml I would expect to work using templates.

```yaml
type: custom:tabbed-card
tabs:
  - card:
      type: shopping-list
      entity: todo.shopping_list
    attributes:
      label: '{{ state_attr(''todo.shopping_list'',''friendly_name'') }}'
      icon: '{{ state_attr(''todo.shopping_list'',''icon'') }}'
```

Displayed:
![image](https://github.com/kinghat/tabbed-card/assets/8419844/fe68bb4e-3003-45ad-8750-3ff678bbc6eb)

Expected:
![image](https://github.com/kinghat/tabbed-card/assets/8419844/b0ad9e23-1e94-4aae-8b8c-ea14ecfd59e3)

**Reply by Selim042** [reply]
And this is my full card using auto-entities, as I would expect it to work with templates:
```yaml
type: custom:auto-entities
filter:
  include:
    - domain: todo
      options:
        card:
          type: shopping-list
          entity: this.entity_id
        attributes:
          label: '{{ state_attr(''todo.shopping_list'',''friendly_name'') }}'
          icon: '{{ state_attr(''todo.shopping_list'',''icon'') }}'
  exclude: []
show_empty: true
card_param: tabs
card:
  type: custom:tabbed-card
  options: {}
```
