### ISSUE TITLE
Invalid Default Lovelace YAML Config

### ISSUE THREAD

**Issue by mathmaniac43** [kinghat/tabbed-card#100]
Hello!

This card is great! I noticed an issue when I set up a new instance of it today that might confuse new users. I am using v0.3.1 via HACS.

When I create a new tabbed card, it defaults to the following YAML:

```yaml
type: custom:tabbed-card
options: {}
tabs:
  - label: Sun
    card:
      type: entity
      entity: sun.sun
```

This causes the card's label to be unpopulated!

![Screenshot_20230418-111824.png](https://user-images.githubusercontent.com/918497/232824311-80b62b78-f601-4603-a70c-1a1f4c73b858.png)

The solution is to move `label` under `attributes`, which you do document well in your README. It would be better if the default YAML config matched the docs.

```yaml
type: custom:tabbed-card
options: {}
tabs:
  - attributes:
      label: Sun
    card:
      type: entity
      entity: sun.sun
```

![Screenshot_20230418-112345.png](https://user-images.githubusercontent.com/918497/232825495-39a1caca-88a8-41c5-bc9c-9535fcb08cee.png)

I did notice that when I updated the card's YAML in the mobile editor, it did not immediately display the change to the label on the tab. I had to save, and then it looked correct on the dashboard and when I re-opened the editor.

Best,
Nick
