### ISSUE TITLE
Tabbed Card + Multiple Entity Row

### ISSUE THREAD

**Issue by candyman2903** [kinghat/tabbed-card#102]
When I try to use the Multiple Entity Row I get an error.

```
type: custom:tabbed-card
styles: ...
tabs:
  - attributes:
      label: Übersicht
    card:
      type: entities
entities:
  - entity: sensor.processor_temperature
    state_header: Temperatur
    type: custom:multiple-entity-row
    name: CPU
```

If anyone has an idea how to fix this, the combination of the two would be just awesome.
