### ISSUE TITLE
Value can't be changed on Windows 11 machine

### ISSUE THREAD

**Issue by Tsarre** [kinghat/tabbed-card#108]
Hello,

I use a combination of the swipe card and the tab card. This works fine on my android phone, but not on a windows machine. On windows (11) I can’t change the value (I don’t get a cursor) ?!

I don't know if this is a problem of the tab card or the swipe card...

So this works fine : 

`
type: custom:tabbed-card
options: {}
tabs:
  - card:
      type: vertical-stack
      cards:
        - type: entities
          entities:
            - entity: input_datetime.tijdstip_alles_uitschakelen
              name: All air conditioning off (again) at
    attributes:
      label: TEST
`

But this doesn't : 

`
type: custom:swipe-card
cards:
  - type: custom:tabbed-card
    options: {}
    tabs:
      - card:
          type: vertical-stack
          cards:
            - type: entities
              entities:
                - entity: input_datetime.tijdstip_alles_uitschakelen
                  name: All air conditioning off (again) at
        attributes:
          label: TEST
`

**Comment by ildar170975** [comment]
1. Post a FORMATTED code. Currently your code is not readable. Place a code inside a triple "`".
![image](https://github.com/kinghat/tabbed-card/assets/71872483/67ee8879-6e79-4d8f-9db9-af1843bae5ba)

2. If your tabbed-card works fine w/o swipe-card - then probably the swipe-card is a culprit. Try this simple code:
```
type: custom:swipe-card
cards:
  - type: entities
    entities:
      - sun.sun
      - sun.sun
      - sun.sun
      - input_text.test_text
      - input_boolean.test_boolean
      - input_number.test_value_uom
      - input_datetime.test_datetime
      - input_select.test_value
      - sun.sun
      - sun.sun

  - type: entities
    entities:
      - sun.sun
      - sun.sun
      - sun.sun
```
![изображение](https://github.com/kinghat/tabbed-card/assets/71872483/3a04ce05-0909-460d-92d0-45f7b5500b76)
Currently in FF & Chrome (Win, at least in Win10 + FF 115.0, Chrome 115.0.5790.171) a user CANNOT edit values in input fields for:
-- input_number (box mode);
-- input_text;
-- input_datetime (for time);
-- input_time.
But it works in Companion App iOS (at least in 15.x.).

There is a workaround - adding this option:
```
type: custom:swipe-card
cards:
  ... 
parameters:
  touchStartPreventDefault: false
```
which allows to edit controls.
