### ISSUE TITLE
Bug after 2023.9 update

### ISSUE THREAD

**Issue by PetitSphincter** [kinghat/tabbed-card#115]
Hi, 

After the 2023.9 update of HA i had this bug :  

![1](https://github.com/kinghat/tabbed-card/assets/60610165/a2e6f747-945b-42d9-850b-635767d272e1)

When i press modify the page to check for parameters it comes back to normal and as it's supposed to look : 

![2](https://github.com/kinghat/tabbed-card/assets/60610165/fba7a48e-60a9-420a-a65d-9028fd926f52)

I have several cards in it, but the parameters i use are the following : 

```css
  - type: custom:tabbed-card
    options: {}
    tabs:

   [...]

    styles:
      '--mdc-theme-primary': white
      '--mdc-tab-color-default': rgba(250, 255, 255, 0.7)
      '--mdc-tab-text-label-color-default': rgba(250, 255, 255, 0.7)
      '--mdc-typography-button-font-size': 10px
      '--mdc-tab-stacked-height': 55px
```

Never had this bug before 2023.9, it happened just after updating and appears everytime i refresh my browserr

**Comment by shaulbd** [comment]
I'm experiencing a similar issue where my icons become oversized and they don't return to their normal size until I enter edit mode.

**Comment by ky13d3nt0n** [comment]
My tabs have completely disappeared after upgrading.

**Comment by kinghat** [comment]
i dont usually update my home ha instance till after the first micro/patch so i havent seen it yet. ill probably take a look at it tomorrow.

**Comment by sdrapha** [comment]
> I'm experiencing a similar issue where my icons become oversized and they don't return to their normal size until I enter edit mode.

Same here, they work after editing the ui, BUT as soon as you refresh the page, they go back to the broken state.

**Comment by SeanChengN** [comment]
Icons become oversized
![x8tp9YgEcj](https://github.com/kinghat/tabbed-card/assets/20624068/79b1fce6-c2be-49ce-a6fb-b330aa2da087)
Normal
![chrome_Mp5GSe3mBV](https://github.com/kinghat/tabbed-card/assets/20624068/028b7554-cae7-4f89-b9df-c3b846a9bf4d)

**Comment by ilearn2023au** [comment]
Facing the same issue immediately after today's update. All tabs are not working.
<img width="211" alt="image" src="https://github.com/kinghat/tabbed-card/assets/140087040/cf2e9764-57d0-4aff-8b9e-973bf03c11ee">

**Comment by jaberhadi** [comment]
I have similar issue, tabs not working only small icon without tabs, I tried to update to the latest beta version then icons become oversized.

**Comment by mathgoy** [comment]
up with the same issue
Hope we get a fix for my most favorite card!

**Comment by notownblues** [comment]
Same here, all tabs are gone

**Comment by uros76** [comment]
Same here, tabs gone :(

**Comment by kulmegil** [comment]
+1

min YAML:
```yaml
type: custom:tabbed-card
tabs:
  - card:
      type: button
      icon: mdi:alpha-a-box
      name: Test Content A
    attributes:
      icon: mdi:numeric-1-box
  - card:
      type: button
      icon: mdi:alpha-b-box
      name: Test Content B
    attributes:
      icon: mdi:numeric-2-box
```
Result: [Screen Shot 2023-09-07 at 17 00 10](https://github.com/kinghat/tabbed-card/assets/570575/df55f82b-593a-4d83-9f73-9cb98448dc8b)
