### ISSUE TITLE
[Bug]: testing issue form

### ISSUE THREAD

**Issue by kinghat** [kinghat/tabbed-card#129]
### Description and outcome

just testing the issue form!

![image](https://github.com/kinghat/tabbed-card/assets/16073360/6879066b-a9a9-47eb-8ead-dbbd237e1574)

### Environment

```Markdown
- OS: Linux
- Browser: firefox
- Home Assistant Version: 2023.9.0
- Tabbed Card Version: 0.3.2
```

### Reproducible configuration

```YAML
type: custom:tabbed-card
tabs:
  - card:
      type: entity
      entity: sun.sun
    attributes:
      label: Sun
```

### Additional context

nothing else to provide!
