### ISSUE TITLE
Attributes not working

### ISSUE THREAD

**Issue by davehahn** [kinghat/tabbed-card#13]
I real love this componet but the attributes  section does not function as described in the readme,

```
type: custom:tabbed-card
tabs:
  - label: 2
    card:
```

function fine but 

```
type: custom:tabbed-card
tabs:
  - attributes:
      label: 2 # local attributes that apply only to individual tabs
      icon: mdi:play
    card:
```
produces a tab with out any label or icon.

Any help would be greatly appreciated.  
Keep up the great work,

Oh this is happenning  on HA 2022.10.0
with the pluggin added through HACS
