### ISSUE TITLE
[Bug]: on new 3.2.3 card_mod: Argument 1 ('target') to MutationObserver.observe must be an instance of Node

### ISSUE THREAD

**Issue by Mariusthvdb** [kinghat/tabbed-card#132]
### Description

been using this mod for a long time with succes, but now have to comment the complete section on `mwc-tab` as shown below.

I dont think there was a change in tabbed-card that made this happen? I noticed it just the other day, after updating card_mod to the 3.2.3 version, which is required for HA 2023.10, as currently in beta.

If anyone spots an obvious fix for this, I would truly appreciate. Missing out in those particular settings is a real setback and I truly hope to be able to get them back, most importantly the mdc-icon-size, and border-color on the indicator.

thanks

### Environment

```Markdown
- OS: [e.g. iOS, Linux] Any device
- Browser: [e.g. chrome, safari] Chrome and Safari
- Home Assistant Version: [e.g. 2023.9.0] 2023.10.0b4       
- Tabbed Card Version: [e.g. 0.3.2] 0.3.2
```

### Reproducible configuration

```YAML
type: custom:mod-card
card_mod:
  style:
    tabbed-card $:
      .: |
        mwc-tab-bar {
          background: {{'var(--lovelace-background)'
                        if states('input_select.theme')|regex_search('(ight|Dark|Matrix)')
                        else 'var(--primary-color)'}};
        }
#       mwc-tab:
#         $:
#           mwc-tab-indicator $: |
#            .mdc-tab-indicator__content--underline {
#               border-color: var(--text-color-off) !important;
#             }
#
#           .: |
#             .mdc-tab {
#               min-width: 80px;
#             }
#             .material-icons {
#               display: contents !important;
#             }
#
#             .mdc-tab--active {
#               --mdc-icon-size: {{states('input_number.active_icon_size')}}px;
#               /*background: var(--text-color-off) !important;*/
#             }

    .: |
      tabbed-card {
        --mdc-tab-horizontal-padding: 0px;
      }
```

### Additional context

<img width="749" alt="Scherm­afbeelding 2023-10-02 om 08 08 07" src="https://github.com/kinghat/tabbed-card/assets/33354141/1cb79ed7-1157-4659-a853-ab29d075c862">
