### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by kllngtme** [kinghat/tabbed-card#135]
### Description

I have each tabbed view show a different NVidia Shield TV instance in my house and all the entities I could find associated to them. One these entities is from the Hyperion integration which shows a streaming video from the device. If the entity is in the tabbed-card, it shows only as a picture and isn't streaming.

The same setup outside of tabbed-card will show the entity streaming .. 

### Environment

```Markdown
- OS: Windows 10
- Browser: Chrome
- Home Assistant Version: 2023.11.1  
- Tabbed Card Version: 0.3.2
```

### Reproducible configuration

```YAML
type: custom:tabbed-card
tabs:
  - attributes:
      label: Living Room
    card:
      type: vertical-stack
      cards:
        - type: vertical-stack
          cards:
            - type: media-control
              entity: media_player.adb_livingroomshield
            - type: media-control
              entity: media_player.plex_mrmc_livingroomshield
            - type: media-control
              entity: media_player.androidremote_livingroomshield
            - type: media-control
              entity: media_player.googlecast_livingroomshield
            - type: picture-entity
              entity: camera.living_room_tv_led
              name: ShieldTV Screen Capture
```
