### ISSUE TITLE
[Bug]: Unable to use conditional cards as tabs

### ISSUE THREAD

**Issue by jeffbeale** [kinghat/tabbed-card#137]
### Description

The tabbed-card ignores all the conditional pieces of the conditional cards and displays the card underneath the conditional card.
![image](https://github.com/kinghat/tabbed-card/assets/72213598/e1f48ab6-e4cc-43a1-9e85-0f203aca8c31)

### Environment

```Markdown
- OS: Linux, Arch-based (garuda)
- Browser: Firefox
- Home Assistant Version: 2023.11.2       
- Tabbed Card Version: 0.3.2
```

### Reproducible configuration

```YAML
type: custom:tabbed-card
options: {}
tabs:
  - attributes:
      label: A
    card:
      type: conditional
      conditions:
        - condition: state
          entity: input_boolean.choresab
          state: 'on'
      card:
        type: todo-list
        entity: todo.chores_weekly_a
        title: Weekly chore list A
  - attributes:
      label: B
    card:
      type: conditional
      name: B
      conditions:
        - condition: state
          entity: input_boolean.choresab
          state: 'off'
      card:
        type: todo-list
        entity: todo.chores_weekly_b
        title: Weekly Chore list B
  - card:
      type: todo-list
      entity: todo.chores_monthly
      title: Monthly chores
    attributes:
      label: M
```
