### ISSUE TITLE
[Bug]: Tabs not showing until editing the dashboard then clicking done

### ISSUE THREAD

**Issue by i00** [kinghat/tabbed-card#146]
### Description

In 0.4.0-alpha the tabs don't show when you initially load the page.
When you edit the dashboard then click save it all shows

### Environment

```Markdown
- OS: Linux
- Browser: Chrome
- Home Assistant Version: 2024.4.4     
- Tabbed Card Version: 0.4.0-alpha
```

### Reproducible configuration

```YAML
type: custom:tabbed-card
tabs:
  - card:
      type: history-graph
      entities:
        - sun.sun
    attributes:
      label: First
  - card:
      show_current: true
      show_forecast: true
      type: weather-forecast
      entity: weather.forecast_home
      forecast_type: daily
    attributes:
      label: Second
```
