### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by elmodem** [kinghat/tabbed-card#149]
### Description

In the mobile app, entity values ​​and unit are sometimes not displayed when using the gauge card type within a horizontal or vertical stack card type.
The issue occurs randomly and will disappear the next time the card is automatically updated.

![tabbed_card](https://github.com/user-attachments/assets/d3f47990-61bb-4de3-ad65-7b6e6c256468)

### Environment

```Markdown
- OS: Android
- Browser: browsers are not affected
- Home Assistant Version: 2024.11.1 core / 20241106.2 frontend       
- Tabbed Card Version: 0.3.2
```

### Reproducible configuration

```YAML
type: custom:tabbed-card
options: {}
tabs:
  - card:
      type: horizontal-stack
      cards:
        - type: gauge
          unit: Watt
          min: -2000
          max: 3000
          needle: true
          severity:
            green: -2000
            yellow: 50
            red: 250
          entity: sensor.strom_aktuell
          name: Aktueller Verbrauch Haus-Strom
        - type: gauge
          needle: true
          severity:
            green: 0
            yellow: 3.5
            red: 5
          entity: sensor.strom_bezug_gesamt_heute
          min: 0
          max: 12
          name: Tagesverbrauch Haus-Strom
    attributes:
      label: ⚡Haus-Strom
  - card:
      type: horizontal-stack
      cards:
        - type: gauge
          unit: Watt
          min: -2000
          max: 3000
          needle: true
          severity:
            green: -2000
            yellow: 50
            red: 250
          entity: sensor.bitshake_smartmeterreader_mt175_power
          name: Aktueller Verbrauch Wärmepumpe
        - type: gauge
          needle: true
          severity:
            green: 0
            yellow: 5
            red: 7.5
          entity: sensor.strom_bezug_wp_tagesverbrauch
          min: 0
          max: 20
          name: Tagesverbrauch Wärmepumpe
    attributes:
      label: ⚡Wärmepumpe
```

### Additional context

Only within the mobile app - browsers are not affected. The issue also existed in earlier HA versions.
