### ISSUE TITLE
[Bug]: graph does not update on tab-switch

### ISSUE THREAD

**Issue by j-mahlke** [kinghat/tabbed-card#150]
### Description

I'm trying to switch between the hour_to_show setting in the graph card by tabs.
The following config renders 24h in every tab, instead of 1/24/168 as set in the tab

The entities are identical in each tab and work as expected, but are cleared here for easier reading 

### Environment

```Markdown
- OS: kubernetes on ubuntu
- Browser: Homeassistant app on android
- Home Assistant Version: 2024.12.5 / Frontend 20241127.8 
- Tabbed Card Version: 0.3.2
```

### Reproducible configuration

```YAML
type: custom:tabbed-card
options: {}
tabs:
  - card:
      type: history-graph
      entities:
        - entity: 
          name: 
        - entity: 
          name: 
        - entity: 
          name: 
        - entity: 
          name: 
        - entity: 
          name: 
    hours_to_show: 1
    attributes:
      label: HOUR
  - card:
      type: history-graph
      entities:
        - entity: 
          name: 
        - entity: 
          name: 
        - entity: 
          name: 
        - entity: 
          name: 
        - entity: 
          name: 
    hours_to_show: 24
    attributes:
      label: DAY
  - card:
      type: history-graph
      entities:
        - entity: 
          name: 
        - entity: 
          name: 
        - entity: 
          name: 
        - entity: 
          name: 
        - entity: 
          name: 
    hours_to_show: 168
    attributes:
      label: WEEK
```
