### ISSUE TITLE
[Bug]: Issues with the map-card since 2025.3

### ISSUE THREAD

**Issue by vingerha** [kinghat/tabbed-card#160]
### Description

I have a setup where each tab shows a map and the position of device(s). 
Since 2025.3 it often does not show the map but a blank screen for each of the tabs. By refreshing the screen it often comes back. The additional thing is that this happens only on my https connection, the local http does not seem to have this issue. I used the core map-card as well as a hacs-map-card and both show the same behavior. 
Before 2025.3.0 all was fine. Tbh I am not 100% sure if this is a map-card issue but the blank screen only appears within the tabbed setup, the same card 'pure' shows fine

### Environment

```Markdown
- OS: [e.g. iOS, Linux]
- Browser: [e.g. chrome, safari]
- Home Assistant Version: [e.g. 2023.9.0]        
- Tabbed Card Version: [e.g. 0.3.2]
```

### Reproducible configuration

```YAML
type: custom:tabbed-card
styles:
  "--mdc-theme-primary": yellow
  "--mdc-tab-text-label-color-default": orange
tabs:
  - card:
      type: custom:map-card
      zoom: 12
      card_size: 8
      history_start: 24 hours ago
      focus_entity:
        - person.arjan
      entities:
        - entity: person.abc
          color: "#16335c"
        - entity: person.def
          color: orange
        - entity: person.ghi
          color: orange
    attributes:
      label: somelabel
```
