### ISSUE TITLE
[Bug]: Picture-Glance entity takes 10 times longer to load

### ISSUE THREAD

**Issue by zavjah** [kinghat/tabbed-card#161]
### Description

Hi there,

I have a few picture-glance entities of my web cameras within a tabbed card and when I open the dashboard the same configuration outside a tabbed card load within a second or two while within a tabbed card it takes almost 10. 

This issue might be related to https://github.com/kinghat/tabbed-card/issues/135 but I decided to start another thread, to be able to track both independently.

Cheers,
Zavjah

### Environment

```Markdown
- OS: HAIS on raspberry 
- Browser: chrome 
- Home Assistant Version: latest      
- Tabbed Card Version: latest
```

### Reproducible configuration

```YAML
type: custom:tabbed-card
    styles:
      "--mdc-theme-primary": steelblue
      "--mdc-tab-text-label-color-default": darkgrey
      "--mdc-typography-button-font-size": 12px
    tabs:
      - attributes:
          label: Außen
        card:
          type: vertical-stack
          cards:
            - type: picture-glance
              camera_view: auto
              image: https://demo.home-assistant.io/stub_config/kitchen.png
              entities: []
              camera_image: camera.haustuer
              card_mod:
                style: |
                  ha-card {
                    margin-top: 10px;
                  }
```
