### ISSUE TITLE
[Bug]: Home Assistant 2025.5.0 deprecated mwc-tab components

### ISSUE THREAD

**Issue by Scags104** [kinghat/tabbed-card#162]
### Description

As seen in the image below. My tabs have now grown so large they take up the whole screen. I have tried clearing cache etc but seems to be a bug with the latest beta.

![Image](https://github.com/user-attachments/assets/4ec12694-f3b3-499a-af55-65353e2fedcd)

### Environment

```Markdown
- OS: Windows/Android App
- Browser: Firefox
- Home Assistant Version: Home Assistant 2025.5.0b0       
- Tabbed Card Version: 0.4.0 alpha 2
```

### Reproducible configuration

```YAML
type: custom:tabbed-card
styles:
  "--mdc-theme-primary": rgb(var(--my-blue))
  "--mdc-tab-text-label-color-default": rgb(var(--my-grey))
tabs:
  - card:
      square: false
      type: grid
      columns: 4
      cards:
        - type: custom:button-card
          template: button_single
          name: mail
          entity: sensor.mail_usps_mail
        - type: custom:button-card
          template: button_single
          name: delivering
          entity: sensor.mail_usps_delivering
        - type: custom:button-card
          template: button_single
          name: delivered
          entity: sensor.mail_usps_delivered
        - type: custom:button-card
          template: button_single
          name: images
          entity: camera.mail_usps_camera
    attributes:
      stacked: true
      label: USPS
      icon: si:usps
  - card:
      square: false
      type: grid
      columns: 3
      cards:
        - type: custom:button-card
          template: button_single
          name: hub
          entity: sensor.mail_amazon_hub_packages
        - type: custom:button-card
          template: button_single
          name: delivered
          entity: sensor.mail_amazon_packages_delivered
        - type: custom:button-card
          template: button_single
          name: images
          entity: camera.mail_amazon_delivery_camera
    attributes:
      stacked: true
      label: Amazon
      icon: si:amazon
  - card:
      square: false
      type: grid
      columns: 3
      cards:
        - type: custom:button-card
          template: button_single
          name: delivering
          entity: sensor.mail_ups_delivering
        - type: custom:button-card
          template: button_single
          name: delivered
          entity: sensor.mail_ups_delivered
    attributes:
      stacked: true
      label: UPS
      icon: si:ups
  - card:
      square: false
      type: grid
      columns: 3
      cards:
        - type: custom:button-card
          template: button_single
          name: delivering
          entity: sensor.mail_fedex_delivering
        - type: custom:button-card
          template: button_single
          name: delivered
          entity: sensor.mail_fedex_delivered
    attributes:
      stacked: true
      icon: si:fedex
      label: FedEx
```
