### ISSUE TITLE
[Bug]: Since 2025.5b tabs not working at all

### ISSUE THREAD

**Issue by tinkerberlin** [kinghat/tabbed-card#163]
### Description

Since updating to 2025.5b I'm not able to use or really see my tabbed cards. See screenshot below. 

<img width="400" alt="Image" src="https://github.com/user-attachments/assets/109ea3b7-f32d-4bec-90c7-dca881217ab4" />

the icons marked in yellow "used to be" nice tabs. 

### Environment

```Markdown
- OS: Windows/Android (all that I use)
- Browser: Chrome
- Home Assistant Version: 2025.5.0b2   
- Tabbed Card Version: not sure; but I had it updated to the newest version
Supervisor 2025.04.1
Operating System 15.2
Frontend 20250502.0

x86 install.
```

### Reproducible configuration

```YAML
type: custom:tabbed-card
options: {}
tabs:
  - label: Lichter
    attributes:
      label: Lichter
      icon: mdi:lightbulb
    card:
      square: true
      columns: 1
      type: grid
      cards:
        - square: true
          columns: 3
          type: grid
          cards:
            - square: true
              columns: 1
              type: grid
              cards:
                - show_name: true
                  show_icon: true
                  type: button
                  tap_action:
                    action: toggle
                  entity: light.flur_dg
                  name: Flur
                  icon: mdi:rug
            - square: true
              columns: 1
              type: grid
              cards:
                - show_name: true
                  show_icon: true
                  type: button
                  tap_action:
                    action: toggle
                  entity: light.treppenhaus_dg
                  name: Treppenhaus
                  icon: mdi:stairs
            - square: true
              columns: 1
              type: grid
              cards:
                - show_name: true
                  show_icon: true
                  type: button
                  tap_action:
                    action: toggle
                  entity: light.schlafzimmer_3
                  name: Schlafzimmer
                  icon: mdi:bed-double
            - square: true
              columns: 1
              type: grid
              cards:
                - show_name: true
                  show_icon: true
                  type: button
                  tap_action:
                    action: toggle
                  entity: light.buro_3
                  name: Büro
                  icon: mdi:laptop
            - square: true
              columns: 1
              type: grid
              cards:
                - show_name: true
                  show_icon: true
                  type: button
                  tap_action:
                    action: toggle
                  entity: light._XXXzimmer_3
                  name: XXXZimmer
                  icon: mdi:teddy-bear
            - square: true
              columns: 1
              type: grid
              cards:
                - show_name: true
                  show_icon: true
                  type: button
                  tap_action:
                    action: toggle
                  entity: light.dimmer_2
                  name: Badezimmer
                  icon: mdi:bathtub
            - square: true
              columns: 1
              type: grid
              cards:
                - show_name: true
                  show_icon: true
                  type: button
                  tap_action:
                    action: toggle
                  entity: light.virtual_balkon
                  name: Balkon
                  icon: mdi:balcony
  - label: Heizung
    attributes:
      label: Heizung
      icon: mdi:radiator
    card:
      square: true
      columns: 1
      type: grid
      cards:
        - square: false
          columns: 2
          type: grid
          cards:
            - type: custom:mushroom-climate-card
              entity: climate.heizung_treppenhausdg
              name: Treppenhaus
              show_temperature_control: true
              collapsible_controls: true
            - type: custom:mushroom-climate-card
              entity: climate.heizung_flurdg
              name: Flur
              show_temperature_control: true
              collapsible_controls: true
            - type: custom:mushroom-climate-card
              entity: climate.heizung_baddg
              name: Badezimmer
              show_temperature_control: true
              collapsible_controls: true
            - type: custom:mushroom-climate-card
              entity: climate.heizung_XXX
              name: XXX
              show_temperature_control: true
              collapsible_controls: true
            - type: custom:mushroom-climate-card
              entity: climate.heizung_schlafzimmer
              name: Schlafzimmer
              show_temperature_control: true
              collapsible_controls: true
            - type: custom:mushroom-climate-card
              entity: climate.heizung_buero
              name: Büro
              show_temperature_control: true
              collapsible_controls: true
  - label: Fenster
    attributes:
      label: Fenster
      icon: mdi:window-closed-variant
    card:
      square: false
      type: grid
      cards:
        - type: custom:mushroom-cover-card
          entity: cover.fenster_bad_roof_window
          fill_container: false
          show_position_control: true
          show_tilt_position_control: false
          show_buttons_control: true
          name: Badezimmer
          visibility:
            - condition: and
              conditions:
                - condition: state
                  entity: cover.rollo_badezimmer_roller_shutter
                  state: open
            - condition: or
              conditions:
                - condition: state
                  entity: cover.fenster_bad_roof_window
                  state: closed
                - condition: state
                  entity: cover.fenster_bad_roof_window
                  state: closing
          icon: mdi:window-closed-variant
          layout: horizontal
        - type: custom:mushroom-cover-card
          entity: cover.fenster_bad_roof_window
          fill_container: false
          show_position_control: true
          show_tilt_position_control: false
          show_buttons_control: true
          name: Badezimmer
          visibility:
            - condition: or
              conditions:
                - condition: state
                  entity: cover.fenster_bad_roof_window
                  state: open
                - condition: state
                  entity: cover.fenster_bad_roof_window
                  state: opening
          icon: mdi:window-open-variant
          layout: horizontal
        - type: custom:mushroom-cover-card
          entity: cover.rollo_badezimmer_roller_shutter
          fill_container: false
          show_position_control: true
          show_tilt_position_control: false
          show_buttons_control: true
          name: Badezimmer
          visibility:
            - condition: or
              conditions:
                - condition: state
                  entity: cover.rollo_badezimmer_roller_shutter
                  state: opening
                - condition: and
                  conditions:
                    - condition: state
                      entity: cover.fenster_bad_roof_window
                      state: closed
                    - condition: state
                      entity: cover.rollo_badezimmer_roller_shutter
                      state: open
          icon: mdi:window-shutter-open
          layout: horizontal
        - type: custom:mushroom-cover-card
          entity: cover.rollo_badezimmer_roller_shutter
          fill_container: false
          show_position_control: true
          show_tilt_position_control: false
          show_buttons_control: true
          name: Badezimmer
          visibility:
            - condition: or
              conditions:
                - condition: state
                  entity: cover.rollo_badezimmer_roller_shutter
                  state: closed
                - condition: state
                  entity: cover.rollo_badezimmer_roller_shutter
                  state: closing
          icon: mdi:window-shutter
          layout: horizontal
        - type: custom:mushroom-cover-card
          entity: cover.fenster_XXX_roof_window
          fill_container: false
          show_position_control: true
          show_tilt_position_control: false
          show_buttons_control: true
          name: XXX
          visibility:
            - condition: and
              conditions:
                - condition: state
                  entity: cover.rollo_xxx_roller_shutter
                  state: open
            - condition: or
              conditions:
                - condition: state
                  entity: cover.fenster_XXX_roof_window
                  state: closed
                - condition: state
                  entity: cover.fenster_XXX_roof_window
                  state: closing
          icon: mdi:window-closed-variant
          layout: horizontal
        - type: custom:mushroom-cover-card
          entity: cover.fenster_XXX_roof_window
          fill_container: false
          show_position_control: true
          show_tilt_position_control: false
          show_buttons_control: true
          name: XXX
          visibility:
            - condition: or
              conditions:
                - condition: state
                  entity: cover.fenster_XXX_roof_window
                  state: open
                - condition: state
                  entity: cover.fenster_XXX_roof_window
                  state: opening
          icon: mdi:window-open-variant
          layout: horizontal
        - type: custom:mushroom-cover-card
          entity: cover.rollo_XXX_roller_shutter
          fill_container: false
          show_position_control: true
          show_tilt_position_control: false
          show_buttons_control: true
          name: XXX
          visibility:
            - condition: or
              conditions:
                - condition: state
                  entity: cover.rollo_XXX_roller_shutter
                  state: opening
                - condition: and
                  conditions:
                    - condition: state
                      entity: cover.fenster_XXX_roof_window
                      state: closed
                    - condition: state
                      entity: cover.rollo_XXX_roller_shutter
                      state: open
          icon: mdi:window-shutter-open
          layout: horizontal
        - type: custom:mushroom-cover-card
          entity: cover.rollo_XXX_roller_shutter
          fill_container: false
          show_position_control: true
          show_tilt_position_control: false
          show_buttons_control: true
          name: XXX
          visibility:
            - condition: or
              conditions:
                - condition: state
                  entity: cover.rollo_xxx_roller_shutter
                  state: closed
                - condition: state
                  entity: cover.rollo_xxx_roller_shutter
                  state: closing
          icon: mdi:window-shutter
          layout: horizontal
        - type: custom:mushroom-cover-card
          entity: cover.fenster_buro_roof_window_2
          fill_container: false
          show_position_control: true
          show_tilt_position_control: false
          show_buttons_control: true
          name: Büro
          visibility:
            - condition: and
              conditions:
                - condition: state
                  entity: cover.rollo_buro_roller_shutter_3
                  state: open
            - condition: or
              conditions:
                - condition: state
                  entity: cover.fenster_buro_roof_window_2
                  state: closed
                - condition: state
                  entity: cover.fenster_buro_roof_window_2
                  state: closing
          icon: mdi:window-closed-variant
          layout: horizontal
        - type: custom:mushroom-cover-card
          entity: cover.fenster_buro_roof_window_2
          fill_container: false
          show_position_control: true
          show_tilt_position_control: false
          show_buttons_control: true
          name: Büro
          visibility:
            - condition: or
              conditions:
                - condition: state
                  entity: cover.fenster_buro_roof_window_2
                  state: open
                - condition: state
                  entity: cover.fenster_buro_roof_window_2
                  state: opening
          icon: mdi:window-open-variant
          layout: horizontal
        - type: custom:mushroom-cover-card
          entity: cover.rollo_buro_roller_shutter_3
          fill_container: false
          show_position_control: true
          show_tilt_position_control: false
          show_buttons_control: true
          name: Büro
          visibility:
            - condition: or
              conditions:
                - condition: state
                  entity: cover.rollo_buro_roller_shutter_3
                  state: opening
                - condition: and
                  conditions:
                    - condition: state
                      entity: cover.fenster_buro_roof_window_2
                      state: closed
                    - condition: state
                      entity: cover.rollo_buro_roller_shutter_3
                      state: open
          icon: mdi:window-shutter-open
          layout: horizontal
        - type: custom:mushroom-cover-card
          entity: cover.rollo_buro_roller_shutter_3
          fill_container: false
          show_position_control: true
          show_tilt_position_control: false
          show_buttons_control: true
          name: Büro
          visibility:
            - condition: or
              conditions:
                - condition: state
                  entity: cover.rollo_buro_roller_shutter_3
                  state: closed
                - condition: state
                  entity: cover.rollo_buro_roller_shutter_3
                  state: closing
          icon: mdi:window-shutter
          layout: horizontal
        - type: custom:mushroom-cover-card
          entity: cover.fenster_schlafzimmer_roof_window
          fill_container: false
          show_position_control: true
          show_tilt_position_control: false
          show_buttons_control: true
          name: Schlafzimmer
          visibility:
            - condition: and
              conditions:
                - condition: state
                  entity: cover.rolladen_schlafzimmer_roller_shutter_2
                  state: open
            - condition: or
              conditions:
                - condition: state
                  entity: cover.fenster_schlafzimmer_roof_window
                  state: closed
                - condition: state
                  entity: cover.fenster_schlafzimmer_roof_window
                  state: closing
          icon: mdi:window-closed-variant
          layout: horizontal
        - type: custom:mushroom-cover-card
          entity: cover.fenster_schlafzimmer_roof_window
          fill_container: false
          show_position_control: true
          show_tilt_position_control: false
          show_buttons_control: true
          name: Schlafzimmer
          visibility:
            - condition: or
              conditions:
                - condition: state
                  entity: cover.fenster_schlafzimmer_roof_window
                  state: open
                - condition: state
                  entity: cover.fenster_schlafzimmer_roof_window
                  state: opening
          icon: mdi:window-open-variant
          layout: horizontal
        - type: custom:mushroom-cover-card
          entity: cover.rolladen_schlafzimmer_roller_shutter_2
          fill_container: false
          show_position_control: true
          show_tilt_position_control: false
          show_buttons_control: true
          name: Schlafzimmer
          visibility:
            - condition: or
              conditions:
                - condition: state
                  entity: cover.rolladen_schlafzimmer_roller_shutter_2
                  state: opening
                - condition: and
                  conditions:
                    - condition: state
                      entity: cover.fenster_schlafzimmer_roof_window
                      state: closed
                    - condition: state
                      entity: cover.rolladen_schlafzimmer_roller_shutter_2
                      state: open
          icon: mdi:window-shutter-open
          layout: horizontal
        - type: custom:mushroom-cover-card
          entity: cover.rolladen_schlafzimmer_roller_shutter_2
          fill_container: false
          show_position_control: true
          show_tilt_position_control: false
          show_buttons_control: true
          name: Schlafzimmer
          visibility:
            - condition: or
              conditions:
                - condition: state
                  entity: cover.rolladen_schlafzimmer_roller_shutter_2
                  state: closed
                - condition: state
                  entity: cover.rolladen_schlafzimmer_roller_shutter_2
                  state: closing
          icon: mdi:window-shutter
          layout: horizontal
      columns: 1
```
