### ISSUE TITLE
[Bug]: Tabbed-card not working with HA 2025.5

### ISSUE THREAD

**Issue by Morriz1971** [kinghat/tabbed-card#164]
### Description

With new update of HA, 2025.5, my tabbed cards doesn't work at all; see image below:

![Image](https://github.com/user-attachments/assets/4bad6dd7-5103-4d0a-886a-031810ba11fb)

### Environment

```Markdown
- OS: [e.g. iOS, Linux]
- Browser: [e.g. chrome, safari]
- Home Assistant Version: [e.g. 2023.9.0]        
- Tabbed Card Version: [e.g. 0.3.2]
```

### Reproducible configuration

```YAML
type: custom:tabbed-card
styles:
  "--mdc-theme-primary": "#FF6600"
  "--mdc-theme-secondary": "#FF6600"
  "--mdc-tab-text-label-color-default": PaleTurquoise
  "--mdc-tab-color-default": PaleTurquoise
  "--mdc-typography-button-font-size": 12px
options:
  defaultTabIndex: 1
tabs:
  - attributes:
      label: Umidità
      icon: fas:tint
      isFadingIndicator: true
      stacked: true
    card:
      entities:
        - entity: sensor.sensore_tup_camera_marcello_umidita
          index: 0
          name: Umidità
          unit: "%"
          color: darkorange
      hour24: true
      hours_to_show: 48
      points_per_hour: 1
      icon: mdi:water-percent
      align_header: right
      align_icon: right
      align_state: left
      line_width: 5
      animate: true
      show:
        average: false
        extrema: false
        fill: fade
        legend: false
        labels: hover
        points: hover
      smoothing: true
      card_mod:
        style: |-
          ha-card
          {
             background: linear-gradient(50deg, rgba(5, 139, 140, 1.0) 30%, rgba(15, 207, 186, 1.0) 100%);
             border: outset 5px rgba(5, 139, 140, 1.0);
          }
      tap_action: more-info
      type: custom:mini-graph-card
  - attributes:
      label: Temperatura
      icon: fas:thermometer-three-quarters
      isFadingIndicator: true
      stacked: true
    card:
      entities:
        - entity: sensor.sensore_tup_camera_marcello_temperatura
          index: 1
          name: Temperatura
          unit: C°
          color: darkorange
      hour24: true
      hours_to_show: 48
      points_per_hour: 1
      icon: mdi:thermometer
      align_header: left
      align_icon: left
      align_state: right
      line_width: 5
      animate: true
      show:
        average: false
        extrema: false
        fill: fade
        legend: false
        labels: hover
        points: hover
      smoothing: true
      card_mod:
        style: |-
          ha-card
          {
             background: linear-gradient(50deg, rgba(5, 139, 140, 1.0) 30%, rgba(15, 207, 186, 1.0) 100%);
             border: outset 5px rgba(5, 139, 140, 1.0);
          }
      tap_action: more-info
      type: custom:mini-graph-card
  - attributes:
      label: Pressione
      icon: fas:tachometer-alt
      isFadingIndicator: true
      stacked: true
    card:
      entities:
        - entity: sensor.sensore_tup_camera_marcello_pressione
          index: 2
          name: Pressione
          unit: pascal
          color: darkorange
      hour24: true
      hours_to_show: 48
      points_per_hour: 1
      icon: mdi:gauge
      align_header: right
      align_icon: right
      align_state: left
      line_width: 5
      animate: true
      show:
        average: false
        extrema: false
        fill: fade
        legend: false
        labels: hover
        points: hover
      smoothing: true
      card_mod:
        style: |-
          ha-card
          {
             background: linear-gradient(50deg, rgba(5, 139, 140, 1.0) 30%, rgba(15, 207, 186, 1.0) 100%);
             border: outset 5px rgba(5, 139, 140, 1.0);
          }
      tap_action: more-info
      type: custom:mini-graph-card
```
