### ISSUE TITLE
[Bug]: Tabs are not displayed

### ISSUE THREAD

**Issue by 0kinawa** [kinghat/tabbed-card#167]
### Description

Tabs are not displayed

### Environment

```Markdown
- OS: HAOS on raspberry 
- Browser: chrome 
- Home Assistant Version: 2025.5.1   
- Tabbed Card Version: 0.3.3
```

### Reproducible configuration

```YAML
cards:


- type: custom:tabbed-card
  tabs:
    - card:
        type: button
        entity: switch.kabinet_svet_left
        tap_action:
          action: toggle
        show_name: true
        show_icon: true
        show_state: true
      attribute:
        label: Button
    - card:
        type: button
        entity: switch.kabinet_svet_right
        tap_action:
          action: toggle
        show_name: true
        show_icon: true
        show_state: true
      attribute:
        label: Button2
```

### Additional context

![Image](https://github.com/user-attachments/assets/84eb0d61-a11d-453b-88c1-180fb4c882d7)
