### ISSUE TITLE
[Bug]: UI editing gone in 2025.5

### ISSUE THREAD

**Issue by Aephir** [kinghat/tabbed-card#168]
### Description

After upgrading to HA 2025.5, my tabbed-cards no longer have UI editing, I can only edit in yaml.

Sreenshot when trying to edit a `tabbed-card` in Lovelace.
<img width="516" alt="Image" src="https://github.com/user-attachments/assets/8286b77d-cf22-41bc-813e-e402a2f16248" />

### Environment

```Markdown
- OS: Home Assistant OS (client OS is either macOS or iOS)
- Browser: Home Assistant iOS client or Firefox on macOS
- Home Assistant Version: 2025.5.1
- Tabbed Card Version: 0.3.3
```

### Reproducible configuration

```YAML
type: custom:tabbed-card
options: {}
tabs:
  - card:
      type: entity
      entity: sun.sun
    attributes:
      label: Sun
```
