### ISSUE TITLE
Hide as default

### ISSUE THREAD

**Issue by YvesZH** [kinghat/tabbed-card#19]
Great card - thanks a lot. 

futurerequest: is it possible to set the default value to 'hide'?  so that only the register is displayed and no content below (all buttons inactive). 
In addition, your card 'remembers' the active register despite switching dashboard and reset to hide in x minutes.

Like this:
```
  - type: custom:tabbed-card
    options:
      defaultTabIndex: hide
      resetToDefault: true #if switch or reload the dashboard
      timeoutToDefault: 5min (or false)

```

Thanks 🙏
