### ISSUE TITLE
some cards fail to fully render

### ISSUE THREAD

**Issue by commentsonly** [kinghat/tabbed-card#30]
I'm quite happy with tabbed-card, but yesterday I felt to make use of
Options:
  defaultTabIndex: 1
it's main function works as declared but I got 2 gauges sitting on TAB 0 and since I start with default tab being 1 what happens is that these gauges don't show values any more. Simply the gauge but the name for example 'temperature' but no value nor the unit.

Any idea?
All get's cured if I remove the defaultTabIndex or turn this to 0.

**Comment by commentsonly** [comment]
Well, duplicated the card, on the detail tag is a plotly graph. So I simply swapped the code so that Klima is the first one on the left side card. And in there I defined defaultTabIndex: 1 so that I had to manually select the left tab named "KLIMA".
As you see the value is gone. Sometimes it gets lost on both gauges, something one of them remains there.
If I wait for a while the missing value/unitofmeasurement comes back.
Looks to me as if there's a missing fresh or such like fetching the last value. Might also be a gauge problem itself, who knows.

pic and the beginning code snippet .....

![Screenshot 2022-10-25 202652](https://user-images.githubusercontent.com/35866491/197852869-014a50ea-bf5a-47cd-816e-1a5b88d8e285.png)

```
type: custom:tabbed-card
options:
  defaultTabIndex: 1
tabs:
  - attributes:
      label: Klima
    card:
      type: horizontal-stack
      cards:
        - type: gauge
          entity: sensor.esp32computerraum_bme680_temp
          name: Temperatur
          severity:
            green: 0
            yellow: 0
            red: 0
        - type: gauge
          entity: sensor.esp32computerraum_bme680_humi
          name: Luftfeuchte
  - attributes:
      label: Detail
    card:
      type: custom:plotly-graph
      entities:

```
