### ISSUE TITLE
Feature request: Hide empty tabs

### ISSUE THREAD

**Issue by Aleborg** [kinghat/tabbed-card#46]
Feature request: 
Would nice to have an option to hide tabs that are empty.

```yaml
attributes?:
  hideIfEmpty?: boolean
```

I'm using type: `custom:auto-entities` so the card can potentially be empty.

```yaml
tabs:
  - card:
      type: custom:auto-entities
      card:
```
