### ISSUE TITLE
Bug: Card not updating in preview

### ISSUE THREAD

**Issue by ITensEI** [kinghat/tabbed-card#50]
Trying to set up the tabbed card and for the life of me couldn't figure out why it's not displaying name or icon in the tab

![image](https://user-images.githubusercontent.com/9561099/205372126-a2b4b738-106f-498a-abc3-457ea46cded1.png)

I re-downloaded the card through HACS which got it to show up, but now I'm noticing that every time I make changes to the card the preview doesn't update until I save it

**Comment by kinghat** [comment]
can you please paste in your exact configuration so i can reproduce locally?

**Comment by ITensEI** [comment]
I was trying with just an example you see in the screenshot. Currently I left it at this for now:
```
type: custom:tabbed-card
tabs:
  - card:
      type: horizontal-stack
      cards:
        - type: custom:mushroom-light-card
          entity: light.living_room
          use_light_color: true
          show_brightness_control: true
          show_color_temp_control: false
          show_color_control: true
          collapsible_controls: true
          hold_action:
            action: more-info
          layout: vertical
        - type: custom:mushroom-light-card
          entity: light.bedroom
          layout: vertical
          use_light_color: true
          show_brightness_control: true
          show_color_temp_control: false
          show_color_control: true
    show_name: true
    show_icon: true
    attributes:
      label: Lights
      icon: mdi:lightbulb-group
  - card:
      type: entity
      entity: sensor.moon_phase
```
But any config does the same for me. I've been noticing some weird glitches with Chrome these last few days where the cards seemingly vanish until I leave the page and return. Not even refresh fixes it. A working card would just fully vanish with seemingly no errors. Now as I'm typing this I check the preview, then back to text and half the text is blank
![image](https://user-images.githubusercontent.com/9561099/205379638-386465ee-ff21-4841-97c3-18dd7bcf01c9.png)
I feel like this might be a browser issue
