### ISSUE TITLE
I cant see the label of the tabs

### ISSUE THREAD

**Issue by idorose** [kinghat/tabbed-card#52]
I'm trying to create a tabbed card for my remotes, each card is vertical stack of horizontal stacks with buttons
I see the tab at the top but the label is not showing, i tried to change the color and font size with the styles but it only changed the color of the ident of the tab and resizing didn't seem to have any affect

I'm using latest HA version (2022.12.0) and I installed manually (added all of the files in SRC folder to resources and the latest release tabbed-card.js).

**Comment by kinghat** [comment]
can you please post a screenshot/cast of the issue and your exact config?

**Comment by idorose** [comment]
![Screenshot_2022-12-10-21-53-58-80_c3a231c25ed346e59462e84656a70e50.jpg](https://user-images.githubusercontent.com/45543838/206872997-1a9c71ca-576c-4f75-81fe-c6624dccade8.jpg)

this is the code:
http://pastie.org/p/0kDBTkLHi4XfyiREODvAWO

but it also happens with the default card showing the sun

**Comment by kinghat** [comment]
thats not following the configuration schema: https://github.com/kinghat/tabbed-card#card-schema

```yaml
type: custom:tabbed-card
tabs:
  - label: Kodi
    card:
      ...
```

should be:

```yaml
type: custom:tabbed-card
tabs:
  - card:
      type:
    attributes?:
      label?: string
```

can you post the same for the default card you are talking about? if youre talking about whats returned form the editor, thats being worked on so isnt functional and you can disregard.
