### ISSUE TITLE
Does not tab in certain browsers

### ISSUE THREAD

**Issue by jofotoo** [kinghat/tabbed-card#61]
I cannot get the other tabs to show in Google Chrome; it never leaves the first tab.   HA iOS app and Safari on Mac do work, though. 

> Home Assistant 2022.12.6
> Supervisor 2022.12.1
> Operating System 9.4
> Frontend 20221213.0 - latest
> 

Let me know if you need further info.

**Comment by kinghat** [comment]
can you post your config and a screenshot or video of the issue please?

**Comment by jofotoo** [comment]
Sure, here's a [video](https://imgur.com/b9hatS3)

Config:

```
type: custom:tabbed-card
styles: ...
tabs:
  - attributes:
      label: Input
    card:
      type: entities
      entities:
        - entity: input_datetime.dog_spray
          type: custom:mushroom-entity-card
          tap_action:
            action: call-service
            service: script.set_a_time
            data:
              ent: input_datetime.dog_spray
        - entity: input_datetime.dog_pill
          type: custom:mushroom-entity-card
          tap_action:
            action: call-service
            service: script.set_a_time
            data:
              ent: input_datetime.dog_pill
        - entity: input_datetime.dog_ate
          type: custom:mushroom-entity-card
        - entity: input_datetime.dog_drank
          type: custom:mushroom-entity-card
        - entity: input_datetime.dog_food_placed
          type: custom:mushroom-template-card
          primary: >-
            Dog food placed @ {{ states('input_datetime.dog_food_placed') |
            as_timestamp | timestamp_custom('%A %m/%d at %I:%M %p') }}
          secondary: >-
            {{ states('input_datetime.dog_food_placed') | as_datetime |
            relative_time }}
          icon: mdi:bowl-mix
          icon_color: >-
            {% if (now() | as_timestamp - 
            state_attr('input_datetime.dog_food_placed', 'timestamp')) /60 > 
            states('input_number.dog_food_expiration_min')| int %}

            #ff0000
             {% elif (now() | as_timestamp -  state_attr('input_datetime.dog_food_placed', 'timestamp')) /60 > (states('input_number.dog_food_expiration_min')| int -30) %}
            #ffff00

            {% endif %}
          tap_action:
            action: call-service
            service: script.set_a_time
            data:
              ent: input_datetime.dog_food_placed
            target: {}
  - attributes:
      label: Output
    card:
      type: entities
      entities:
        - entity: input_datetime.dog_walked
          type: custom:mushroom-entity-card
        - entity: input_datetime.dog_peed
          type: custom:mushroom-entity-card
        - entity: input_datetime.dog_pooped
          type: custom:mushroom-entity-card
```
