### ISSUE TITLE
Max width on iOS companion app does not match web version....

### ISSUE THREAD

**Issue by MajorAutomation** [kinghat/tabbed-card#64]
Thanks for your hard work on this project, it is awesome.

I am having an issue on the companion app that is not scaling the tab headers down as per the web interface.

Here is my code:

styles:
  '--mdc-theme-primary': orange
  '--mdc-tab-text-label-color-default': white
  '--mdc-typography-button-font-size': 11px
  '--mdc-tab-height': 24px
  '--mdc-tab-horizontal-padding': 0px
attributes:
  isMinWidthIndicator: true
  minWidth: true
  isFadingIndicator: true
options: {}

This is what the web interface looks like (perfect)

<img width="502" alt="Screenshot 2023-01-08 at 11 49 11 am" src="https://user-images.githubusercontent.com/59648489/211176449-79635640-da5f-41a9-9364-af7147353cce.png">

But the mobile companion app does not scale the names across the top correctly? Is there a fix for this as all headers should fit nicely, but I am missing the 5th entity tab name and you have to scroll? I have tried taking the font size down to 6px and there is more than ample room to fit the last entity?

![image](https://user-images.githubusercontent.com/59648489/211176634-2d880ced-ed53-4b59-be93-94f44e5b8d70.png)

Thanks

**Comment by kinghat** [comment]
i dont have an ios device to test the apps webview on but it looks to be functioning properly. you have enough tabs that it is going to shrink them as small as possible to fit as many as possible. you can see this if you comment out 3 of the tabs and watch them fill the tab bar. like this:

![image](https://user-images.githubusercontent.com/16073360/211179431-8c3f38e5-4af1-4c02-9b37-2a335d9de56b.png)

its because of the smaller screen size. your tabs that are not showing are just out of view and you should be able to scroll over to see them. its not very intuitive but i will be adding scroll arrows for when the tabs overflow. does this make sense?

**Comment by MajorAutomation** [comment]
There are huge gaps between the tabs though (Dining ->Living ->Bedroom), I have set padding to 0px, if it can't be done, I guess I have to scroll. 
Thanks for the quick response

**Comment by kinghat** [comment]
> There are huge gaps between the tabs though (Dining ->Living ->Bedroom), I have set padding to 0px, if it can't be done, I guess I have to scroll. Thanks for the quick response

oh, um you shouldnt need quotes on your style keys. is everything indented properly?
this works for me:

```yaml
styles:
  --mdc-tab-horizontal-padding: 0px
 ```

![image](https://user-images.githubusercontent.com/16073360/211179943-9a020241-48b8-46d5-9ad0-5be43d53b1ff.png)

**Comment by MajorAutomation** [comment]
HA seems to be adding these quotes, I remove them and they come back, the colour options appear to be working ok with quotes as does the font size and tab height. They don't seem to get any closer for me.

Here is all my code....

type: custom:tabbed-card
styles:
  '--mdc-theme-primary': orange
  '--mdc-tab-text-label-color-default': white
  '--mdc-typography-button-font-size': 9px
  '--mdc-tab-height': 24px
  '--mdc-tab-horizontal-padding': 0px
attributes:
  isMinWidthIndicator: true
  minWidth: true
  isFadingIndicator: true
options: {}
tabs:
  - card:
      type: custom:mushroom-climate-card
      entity: climate.aircon_1
      name: Dining Room
      collapsible_controls: false
      layout: horizontal
      use_entity_picture: true
      tap_action:
        action: more-info
      hvac_modes:
        - 'off'
        - fan_only
        - heat
        - cool
    attributes:
      label: Dining
  - card:
      type: custom:mushroom-climate-card
      entity: climate.aircon_2
      collapsible_controls: false
      layout: horizontal
      use_entity_picture: true
      tap_action:
        action: more-info
      hvac_modes:
        - 'off'
        - fan_only
        - heat
        - cool
    attributes:
      label: Living
  - card:
      type: custom:mushroom-climate-card
      entity: climate.aircon_3
      collapsible_controls: false
      layout: horizontal
      use_entity_picture: true
      tap_action:
        action: more-info
      hvac_modes:
        - 'off'
        - fan_only
        - heat
        - cool
    attributes:
      label: Bedroom
  - card:
      type: custom:mushroom-climate-card
      entity: climate.aircon_4
      collapsible_controls: false
      layout: horizontal
      use_entity_picture: true
      tap_action:
        action: more-info
      hvac_modes:
        - 'off'
        - fan_only
        - heat
        - cool
    attributes:
      label: Tyler
  - card:
      type: custom:mushroom-climate-card
      entity: climate.aircon_5
      collapsible_controls: false
      layout: horizontal
      use_entity_picture: true
      tap_action:
        action: more-info
      hvac_modes:
        - 'off'
        - fan_only
        - heat
        - cool
    attributes:
      label: Jaxson

**Comment by kinghat** [comment]
where are you entering and copying this config from?

**Comment by kinghat** [comment]
> where are you entering and copying this config from?

regardless, your yaml config needs proper indentation to be accurate. this is correct formatting and works:
```yaml
type: custom:tabbed-card
attributes:
  minWidth: true
  isMinWidthIndicator: true
styles:
  '--mdc-tab-horizontal-padding': 0px
tabs:
  - card:
      ...
    attributes:
      ...
```

**Comment by MajorAutomation** [comment]
This is the layout of the code, looks ok and passed YAML checker...

https://pastebin.com/B5nBmtvK

**Comment by kinghat** [comment]
> This is the layout of the code, looks ok and passed YAML checker...
> 
> https://pastebin.com/B5nBmtvK

weird. i dont have a ios device to check that. can you add this config and see if it has the same issue?
```yaml
type: custom:tabbed-card
attributes:
  minWidth: true
  isMinWidthIndicator: true
styles:
  '--mdc-tab-horizontal-padding': 0px
tabs:
  - card:
      type: entity
      entity: sun.sun
    attributes:
      icon: mdi:pause
      label: Pause
  - card:
      type: entity
      entity: sun.sun
    attributes:
      label: Play
      icon: mdi:play
  - card:
      type: entity
      entity: sun.sun
    attributes:
      icon: mdi:stop
      label: Stop
  - card:
      type: entity
      entity: sun.sun
    attributes:
      icon: mdi:pause
      label: Pause
```
