### ISSUE TITLE
Doesnt work with "Simple Thermostat"

### ISSUE THREAD

**Issue by Bone84** [kinghat/tabbed-card#68]
Hi,

there is a Bug with [Simple Thermostat](https://github.com/nervetattoo/simple-thermostat).

If I use "type: custom:simple-thermostat" the Tab with Simple Thermostat shows Nothing below the Tab. If I change the type to "thermostat" or "custom:better-thermostat-ui-card" it works fine.

```
type: custom:tabbed-card
tabs:
  - attributes:
      label: Bad
    card:
      type: vertical-stack
      cards:
        - type: custom:vertical-stack-in-card
          cards:
            - type: custom:better-thermostat-ui-card
              entity: climate.bad_bt
              disable_window: true
              name: Bad
              eco_temperature: 19
            - type: glance
              show_icon: true
              show_name: false
              entities:
                - entity: binary_sensor.lumi_lumi_sensor_magnet_aq2_opening
                - entity: binary_sensor.shellyflood_349454713515_flood
  - attributes:
      label: Wohnzimmer
    card:
      type: vertical-stack
      cards:
        - type: custom:vertical-stack-in-card
          cards:
            - type: custom:simple-thermostat
              entity: climate.heizung
            - type: glance
              show_icon: true
              show_name: false
              entities:
                - entity: binary_sensor.lumi_lumi_sensor_magnet_aq2_opening
                - entity: binary_sensor.shellyflood_349454713515_flood
  - attributes:
      label: Arbeitszimmer
    card:
      type: vertical-stack
      cards:
        - type: custom:vertical-stack-in-card
          cards:
            - type: thermostat
              entity: climate.heizung_az
              header: null
            - type: glance
              show_icon: false
              entities:
                - entity: sensor.heizung_az_next_scheduled_change_time
                  name: Änderung
                - entity: sensor.heizung_az_comfort_temperature
                  name: Komfort
                - entity: sensor.heizung_az_eco_temperature
                  name: Eco


```
![Screen1](https://user-images.githubusercontent.com/29546649/211598648-39047ce2-a9cf-4d58-8454-d436f6ee6c8e.jpg)
![Screen2](https://user-images.githubusercontent.com/29546649/211598656-5cce29a5-cc1a-4386-b3e7-2a55df8bb7a4.jpg)
![Screen3](https://user-images.githubusercontent.com/29546649/211598664-9290facd-75fb-4635-975a-b7485e1ceb7d.jpg)

**Comment by kinghat** [comment]
that repo says to use the updated card: https://github.com/dadge/simple_thermostat#warning--this-repo-is-not-longer-maintained-please-consider-switch-tho-the-new-one--httpsgithubcomdadgeawesome_thermostat

not saying thats the problem but i would check that out. otherwise im not sure what the issue could be offhand. try moving the order of card around. it could be related to: https://github.com/kinghat/tabbed-card/issues/30

**Comment by Bone84** [comment]
sorry, i linked the wrong simple thermostat...
https://github.com/nervetattoo/simple-thermostat[this is the right one](https://github.com/nervetattoo/simple-thermostat) 

moving the order of the cards has no effect. always the tab with simple thermostat is empty.

**Comment by kinghat** [comment]
so its all good now?

**Comment by Bone84** [comment]
no it still doesnt work, accidentally clicked on the close button, sorry.

**Comment by kinghat** [comment]
> no it still doesnt work, accidentally clicked on the close button, sorry.

thanks for the reply. i tried with the equivalent stock ha cards and its seems fine:

https://user-images.githubusercontent.com/16073360/213304968-4ed31132-58f9-408a-9c66-9f05bfed7662.mp4

that config:

```yaml
type: custom:tabbed-card
tabs:
  - card:
      type: vertical-stack
      cards:
        - type: thermostat
          entity: climate.ecobee
          name: bad
        - type: glance
          entities:
            - sensor.hacs
            - sensor.carbon_dioxide
            - sensor.carbon_monoxide
    attributes:
      label: Bad
  - card:
      type: vertical-stack
      cards:
        - type: thermostat
          entity: climate.ecobee
        - show_name: false
          show_icon: true
          show_state: true
          type: glance
          entities:
            - sensor.hacs
            - sensor.carbon_dioxide
            - sensor.carbon_monoxide
    attributes:
      label: Wohnzimmer
  - card:
      type: vertical-stack
      cards:
        - type: thermostat
          entity: climate.ecobee
        - show_name: true
          show_icon: false
          show_state: true
          type: glance
          entities:
            - sensor.hacs
            - sensor.carbon_dioxide
            - sensor.carbon_monoxide
    attributes:
      label: Arbeitszimmer
```

maybe try that config and see if it works or not. also you have a `header: null` in your third tab that probably shouldnt be there.
