### ISSUE TITLE
Icon not vertically centered

### ISSUE THREAD

**Issue by ildar170975** [kinghat/tabbed-card#82]
Compare these variants:

![изображение](https://user-images.githubusercontent.com/71872483/218603851-fcf01185-92fb-477b-9f35-3a11200b4b07.png)

The 2nd variant is a default view, the 1st variant is styled by card-mod:
```
type: vertical-stack
cards:
  - type: custom:mod-card
    card_mod:
      style:
        tabbed-card $:
          mwc-tab: |
            ha-icon {
              display: inline-flex;
            }
    card:
      type: custom:tabbed-card
      attributes:
        icon: mdi:circle
      tabs: &ref_tabs
        - card:
            type: entities
            entities:
              - sun.sun
          attributes:
            label: label 1
        - card:
            type: entity
            entity: sun.sun
          attributes:
            label: label 2
  - type: custom:tabbed-card
    attributes:
      icon: mdi:circle
    tabs: *ref_tabs
```
I suggest to use the `display: inline-flex` style as a default.
