### ISSUE TITLE
Suggestion: vivid tabs

### ISSUE THREAD

**Issue by ildar170975** [kinghat/tabbed-card#83]
Currently tabs have no border & background.
I suggest to make tabs more vivid.
It can be done by CSS styles.
Check my proposals below.
I am using card-mod to inject CSS properties.

Current default view with a default theme:

![изображение](https://user-images.githubusercontent.com/71872483/218641573-efad4786-80d9-4c71-9c90-08ad52b73a56.png)

```
  - type: custom:tabbed-card
    attributes:
      icon: mdi:circle
    tabs:
      - card:
          type: entities
          entities:
            - sun.sun
        attributes:
          label: label 1
      - card:
          type: entity
          entity: sun.sun
        attributes:
          label: label 2
```

Suggestion:

![изображение](https://user-images.githubusercontent.com/71872483/218641884-a151dbf9-0eb4-4df7-aa1e-ed5fcf4e4d1f.png)

```
  - type: custom:mod-card
    card_mod:
      style:
        tabbed-card:
          $: |
            mwc-tab {
              background: var(--ha-card-background, var(--card-background-color, white) );
              border-color: var(--ha-card-border-color, var(--divider-color, #e0e0e0) );
              border-width: 1px;
              border-top-left-radius: 12px;
              border-top-right-radius: 12px;
              border-style: solid;
              overflow: hidden;
            }
            section article > * {
              --ha-card-border-radius: 0px 0px 12px 12px;
            }
    card:
      type: custom:tabbed-card
      attributes:
        icon: mdi:circle
      tabs:
        - card:
            type: entities
            entities:
              - sun.sun
          attributes:
            label: label 1
        - card:
            type: entity
            entity: sun.sun
          attributes:
            label: label 2
```
