### ISSUE TITLE
FR: add tooltip

### ISSUE THREAD

**Issue by Mariusthvdb** [kinghat/tabbed-card#85]
please consider adding a tooltip option to the tabs.
Using an icon only tabbed config (because the labels are not resizable and force us to swipe the tabs) it would be really nice to have a tooltip on hovering.
Just like the tooltip in the main header bar

if it could be done with configurable transition, even better

using this myself on all button-cards to give you an idea:
```
  styles:
    tooltip:
      - transition: opacity 0.5s. # <-- main concern here, and makes the tooltip immediate
      - color: var(--card-background-color)
      - font-size: 12px
      - background: var(--primary-color)
      - padding: 5px
      - border-width: 0px
```

thanks for considering!
