### ISSUE TITLE
Dropdown (input_select) truncated by card with no way to scroll

### ISSUE THREAD

**Issue by kylepyke** [kinghat/tabbed-card#96]
Thanks for all of your work on this! I'm using an input_select dropdown, but the options are chopped off at the bottom of the card. Perhaps this is a limit of HA, but is there a workaround to scroll the through the list? See attached picture for example.
<img width="528" alt="Screen Shot 2023-03-16 at 1 58 34 AM" src="https://user-images.githubusercontent.com/107963487/225539181-4414dde2-9b66-4f51-8817-6f67f49c0f96.png">

**Comment by ildar170975** [comment]
Seems the tabbed-card does not have any own clipping:
![image](https://user-images.githubusercontent.com/71872483/225693030-3e31c560-8355-43a0-ad23-7286b4d13a8d.png)
```
type: custom:mod-card
card:
  type: custom:tabbed-card
  tabs:
    - card:
        type: entities
        entities:
          - input_select.fan_kitchen_speed
      attributes:
        label: label 1
    - card:
        type: entities
        entities:
          - sun.sun
      attributes:
        label: label 2
```
Check other cards you use on the tab.
