### ISSUE TITLE
No tab titles

### ISSUE THREAD

**Issue by ricardoboss** [kinghat/tabbed-card#98]
I have the macos-ui-theme installed (not sure if that's the problem) and the tab titles are missing:

<img width="397" alt="image" src="https://user-images.githubusercontent.com/6266356/227718813-357db142-2d5e-4057-ad60-c05c168a9aea.png">

This might be because there was no label rendered in HTML:

<img width="592" alt="image" src="https://user-images.githubusercontent.com/6266356/227718863-32a0ed4e-a393-4884-a7a3-6b757d3cb7a5.png">

This is the source:

```yaml
type: custom:tabbed-card
tabs:
  - label: Täglich
    card:
      type: custom:weather-card
      number_of_forecasts: '5'
      current: true
      details: false
      forecast: true
      hourly_forecast: false
      entity: weather.bremen_daily
  - label: Stündlich
    card:
      type: custom:hourly-weather
      entity: weather.bremen_hourly
      num_segments: '8'
      icons: true
      label_spacing: '2'
      name: Stündliches Wetter
      show_precipitation_amounts: true
      offset: '0'
      show_precipitation_probability: true
```

**Comment by ildar170975** [comment]
Check docs for a correct placement of the “label” option.

**Comment by ricardoboss** [comment]
Ah thanks!

This is the fixed code:

```yaml
type: custom:tabbed-card
tabs:
  - attributes:
      label: Stündlich
    card:
      type: abc
  - attributes:
      label: Täglich
    card:
      type: xyz
```
